In [1]:
import pandas as pd

df = pd.read_csv("../data/clean/upworthy-archive-exploratory-packages-03.12.2020 (1).csv", parse_dates=["created_at", "test_start"])
df.shape

(22666, 18)

In [2]:
tests = df.groupby("clickability_test_id").agg(
    start = ("test_start", "first"),
    problem = ("problem", "first"),
    n_packages = ("clicks", "size"),   
    
)
tests["problem"].sum()

1050

In [3]:
df.groupby("clickability_test_id")["problem"].nunique().max()

1

In [4]:
flagged = tests[tests["problem"] == 1]["start"]
flagged.min(), flagged.max()

('2013-06-25 03:38:33.509000+00:00', '2014-01-10 20:40:44.428000+00:00')

In [12]:
tests.sort_values("start").query("problem == 0").loc[lambda t: t["start"] < "2013-06-25"].tail(3)

,start,problem,n_packages
clickability_test_id,,,
51c7b78f9e61d4d06c0040db,2013-06-24 03:08:24.803000+00:00,0,4
51c8cc33bd57ec06e200319e,2013-06-24 22:46:35.771000+00:00,0,4
51c8cece234062bbdd003366,2013-06-24 22:57:41.848000+00:00,0,4

In [14]:
tests.sort_values("start").query("problem == 0").loc[lambda t: t["start"] >= "2014-01-11"].head(3)

,start,problem,n_packages
clickability_test_id,,,
52d0ad1b1229172bb2000a47,2014-01-11 02:32:34.622000+00:00,0,2
52d0ce5ddce55b11c50004b9,2014-01-11 04:55:20.697000+00:00,0,4
52d1c8cb011cf1f8ca001a37,2014-01-11 22:43:00.479000+00:00,0,4